development:
  adapter: postgresql
  database: db/development.postgresql
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: db/test.postgresql
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production.postgresql
  host: localhost
  pool: 5
  timeout: 5000
